name: Integration tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  happy-path-geth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Prune cache to keep the size down
        run: docker builder prune -af && docker system prune -af
      - name: Run all up happy-path test
        run: tests/all-up-test.sh
  happy-path-hardhat:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run all up happy-path test
        run: tests/all-up-test.sh
        env:
          HARDHAT: True
  validator-out:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run all up test with a validator out
        run: tests/all-up-test.sh VALIDATOR_OUT
  valset-stress:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run all up valset stress test
        run: tests/all-up-test.sh VALSET_STRESS
  batch-stress:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run all up batch stress test
        run: tests/all-up-test.sh BATCH_STRESS
  v2-happy-path:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run all up batch stress test
        run: tests/all-up-test.sh V2_HAPPY_PATH
#  relay-market:
#    runs-on: ubuntu-latest
#    needs: happy-path-geth
#    steps:
#      - uses: actions/checkout@v2
#      - uses: satackey/action-docker-layer-caching@v0.0.11
#        with:
#          key: integration-test-cache-{hash}
#          restore-keys: |
#            integration-test-cache-
#      - name: Run all up relay market test
#        env:
#          ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
#          NO_IMAGE_BUILD: True
#        if: ${{ env.ALCHEMY_ID != '' }}
#        run: tests/all-up-test.sh RELAY_MARKET $ALCHEMY_ID
  orchestrator-keys:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run orchestrator key setting test
        run: tests/all-up-test.sh ORCHESTRATOR_KEYS
  valset_update_rewards:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run the validator set update rewards test
        run: tests/all-up-test.sh VALSET_REWARDS
  evidence_based_slashing:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run the evidence based slashing test
        run: tests/all-up-test.sh EVIDENCE
  transaction-cancel:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Run the transaction cancel test
        run: tests/all-up-test.sh TXCANCEL
  invalid-events:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Submit invalid events
        run: tests/all-up-test.sh INVALID_EVENTS
  unhalt-bridge:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Halt bridge with ETH hardfork and then unhalt the bridge via governance
        run: tests/all-up-test.sh UNHALT_BRIDGE
  pause-bridge:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Pause and then resume the bridge via governance
        run: tests/all-up-test.sh PAUSE_BRIDGE
  deposit-overflow:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Submit an overflowing deposit
        run: tests/all-up-test.sh DEPOSIT_OVERFLOW
  ethereum-blacklist:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Attempt to deposit to a blacklisted address
        run: tests/all-up-test.sh ETHEREUM_BLACKLIST
  airdrop_proposal:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Execute a governance powered airdrop
        run: tests/all-up-test.sh AIRDROP_PROPOSAL
  signature_slashing:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Test slashing for unsubmitted signatures
        run: tests/all-up-test.sh SIGNATURE_SLASHING
  slashing_delegation:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Test delegation after slashing
        run: tests/all-up-test.sh SLASHING_DELEGATION
  ibc_metadata:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Test setting metadata for IBC tokens
        run: tests/all-up-test.sh IBC_METADATA
  erc721_happy_path:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Test ERC721 happy path
        run: tests/all-up-test.sh ERC721_HAPPY_PATH
  upgrade_test:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Test enterupgradenamestate upgrade
        run: tests/run-upgrade-test.sh v1.6.5
  ibc_auto_forward_test:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Test Eth->Gravity IBC Auto-Forwarding
        run: tests/all-up-test.sh IBC_AUTO_FORWARD
  ethereum_keys:
    runs-on: ubuntu-latest
    needs: happy-path-geth
    steps:
      - uses: actions/checkout@v2
        with:
          key: integration-test-cache-{hash}
          restore-keys: |
            integration-test-cache-
      - name: Test Ethereum Keys signing support between deep_space and Gravity Bridge Chain
        run: tests/all-up-test.sh ETHEREUM_KEYS
